In [36]:
import numpy as np
from datetime import datetime

In [42]:
A = np.random.randint(100, size = (16,16))
A

array([[52, 75, 80, 15, 18,  1, 75, 88, 98, 18, 32, 19, 33, 48,  4, 33],
       [79, 67, 66, 85, 30, 80, 60, 76, 31, 73, 57, 45, 60, 92,  8, 16],
       [41, 12, 40, 14, 80, 82, 73, 42, 46, 83, 97, 86, 30, 75, 70, 87],
       [65, 26,  8, 30, 59,  1, 88, 36, 36, 61, 43, 63, 75, 72, 61, 75],
       [76, 51, 46, 60, 77, 38, 20, 65,  3, 55, 45, 75, 32, 40, 77, 61],
       [59, 85, 82, 11, 51, 39, 67, 53, 58, 78, 60, 57, 73, 12, 65, 59],
       [82, 30, 64,  0, 41, 26, 33, 23, 30, 79,  7, 66, 73, 21, 85, 89],
       [60, 15, 55, 55, 41, 97, 74, 97,  2, 11, 11, 65, 71, 86, 23, 44],
       [13, 15,  7, 11, 52, 71, 56, 97, 14,  3, 71, 98, 74, 17, 95, 31],
       [53, 56,  2, 50, 39, 10, 14, 42, 76, 62, 37, 71, 75, 22, 26, 69],
       [97, 53, 43, 50, 86, 43, 50, 45, 46, 49, 60, 23, 52,  1, 48, 94],
       [50, 14, 47, 76,  6, 22, 72, 64, 15, 83, 73, 28, 55, 89, 81, 17],
       [71, 85, 25, 56, 98, 63, 39, 50,  0,  0,  6,  6,  5, 30,  1, 53],
       [48, 89, 72, 80, 83, 29, 37, 16, 52,  1, 30,

In [43]:
B = np.random.randint(100, size = (16, 16))
B

array([[97, 72, 31, 59, 26, 11, 94, 11,  9, 13, 37, 37, 69, 36, 78, 48],
       [55, 52, 36,  6, 55,  7, 39, 30, 61,  4, 59, 26, 46, 12, 77, 48],
       [77, 70, 26, 95, 14, 71, 76, 88, 85, 52,  2, 86, 76, 66, 45,  8],
       [78, 55, 55, 60, 85, 13, 99, 20, 20,  0, 82, 18, 77, 51,  5, 47],
       [70, 55, 74, 33, 90, 92, 32, 66, 54, 53, 22,  8, 48, 89, 67, 48],
       [77,  3, 30, 71, 71, 60, 56, 25, 58, 17, 39, 18, 94, 46,  7, 36],
       [20, 49, 57, 85, 69, 28,  5, 64, 80, 40,  4, 10, 91, 63, 80, 86],
       [96, 52, 46, 61, 24, 46, 61, 95, 43, 50, 69,  3, 76, 38, 63, 42],
       [60, 42, 51, 67, 41, 92, 34, 33, 12,  9, 36, 33, 42, 87,  8, 55],
       [36, 12, 46,  1, 89, 58, 33, 71, 20, 60, 51, 31, 17, 70, 85, 41],
       [84, 61, 93,  7, 64, 64,  7, 22, 41, 85, 90, 31, 15, 21,  0, 54],
       [24, 53, 59, 32, 66, 93, 33, 20, 36,  0, 39, 41, 79, 31, 88, 17],
       [88, 81, 32, 50, 54, 45, 21, 91, 80, 80, 13, 48, 97,  0, 75, 33],
       [94, 31, 99, 23, 40, 86, 48, 14,  1, 51, 21,

In [44]:
t0 = datetime.now()
C = A @ B
time = datetime.now() - t0
print(time * 1e9)
C

11 days, 13:13:20


array([[46465, 36925, 33839, 34940, 30787, 37189, 32875, 35871, 31930,
        25098, 27344, 21028, 39542, 36572, 37455, 34201],
       [65036, 44121, 47623, 42632, 50314, 46876, 46765, 42015, 38773,
        34265, 39766, 26593, 55079, 46192, 46367, 44180],
       [57670, 42119, 53020, 40201, 53149, 59310, 42379, 45789, 43672,
        42974, 45039, 27101, 47566, 52282, 48603, 50113],
       [47984, 39719, 43307, 33687, 43022, 43781, 35875, 40122, 36046,
        35639, 35500, 22197, 41474, 41470, 47176, 44449],
       [52495, 39519, 41921, 35777, 43297, 42694, 43846, 40383, 36721,
        33326, 41445, 24480, 44126, 40039, 44390, 40205],
       [55229, 44868, 43120, 41545, 46568, 47863, 41111, 49284, 46169,
        38936, 40297, 30226, 50260, 42723, 51062, 43577],
       [43786, 36503, 33423, 34198, 36138, 40829, 38842, 41529, 37181,
        33260, 33165, 26711, 39785, 36753, 46245, 36496],
       [56234, 39032, 40293, 42410, 41327, 43758, 42412, 40335, 38569,
        30923, 32109, 2183

In [45]:
def generateHEXdata(A, B):
    
    matrixes = [A, B.T]
    
    for index, matrix in enumerate(matrixes):
        hexData = []
        for row in matrix:
            tempRowHex = ""
            for col in row:
                tempColHex = hex(col)[2:].zfill(8)
                tempRowHex += tempColHex

            tempRowHex = tempRowHex.ljust(128, '0')
            hexData.append(tempRowHex)
            
        for i in range(16):
            
            try:
                x = " @(posedge CLK) #1 DataIn = "
                y ="512'h" + hexData[i]
                z = f"; InAddress = 5'h{index}{hex(i)[2:]};"
                
                print(x + y + z)
                
            except IndexError:
                pass
            
        print("\n\n\n\n\n")

In [46]:
generateHEXdata(A, B)

 @(posedge CLK) #1 DataIn = 512'h000000340000004b000000500000000f00000012000000010000004b000000580000006200000012000000200000001300000021000000300000000400000021; InAddress = 5'h00;
 @(posedge CLK) #1 DataIn = 512'h0000004f0000004300000042000000550000001e000000500000003c0000004c0000001f00000049000000390000002d0000003c0000005c0000000800000010; InAddress = 5'h01;
 @(posedge CLK) #1 DataIn = 512'h000000290000000c000000280000000e0000005000000052000000490000002a0000002e0000005300000061000000560000001e0000004b0000004600000057; InAddress = 5'h02;
 @(posedge CLK) #1 DataIn = 512'h000000410000001a000000080000001e0000003b000000010000005800000024000000240000003d0000002b0000003f0000004b000000480000003d0000004b; InAddress = 5'h03;
 @(posedge CLK) #1 DataIn = 512'h0000004c000000330000002e0000003c0000004d00000026000000140000004100000003000000370000002d0000004b00000020000000280000004d0000003d; InAddress = 5'h04;
 @(posedge CLK) #1 DataIn = 512'h0000003b00000055000000520000000b0000003300000027000000430