In [1]:
import numpy as np
from datetime import datetime

## TEST 1

In [2]:
A = np.random.randint(100, size = (16,16))
A

array([[16, 40, 17, 73, 85, 87,  8, 31, 12, 49, 62, 76, 99,  5, 40, 20],
       [ 5, 83,  3, 84, 89, 51, 98, 85, 55, 12, 41, 61, 54, 70, 99, 53],
       [73,  8, 57, 73, 81, 61, 46, 22, 24, 18, 13,  0, 63, 95, 50, 17],
       [86,  2, 72, 19, 25,  8, 85, 72, 89,  0, 33, 81, 98, 99, 60, 48],
       [74, 65, 28, 40, 10, 88,  6, 83, 34, 52, 27, 58, 38, 48, 59, 65],
       [40, 79, 58, 74, 69, 43,  1, 88, 79, 67, 27, 43, 51, 52, 37, 18],
       [51, 31, 71, 95, 12, 51, 47, 94, 92, 16, 91,  5, 15, 53, 65, 39],
       [23, 89, 66, 59, 79, 88, 52, 92, 67, 46, 49,  7, 24, 24, 65, 40],
       [ 7, 50, 13, 80, 92, 12, 58, 60,  4,  0, 20, 56, 91, 19, 70,  8],
       [45, 26, 63, 14, 95, 98, 42, 41, 49, 82, 76, 98, 16, 84, 42, 97],
       [40, 77, 49, 28, 13, 38,  3,  0, 50, 34, 65, 44, 89, 95, 92, 68],
       [23, 27, 68, 61, 13, 80,  9, 23, 32, 79, 91, 58, 89, 99, 42,  6],
       [10, 84, 17, 27, 97, 49, 29, 68, 11, 48, 81, 55, 12,  5, 34, 81],
       [68, 35, 83, 92, 96, 42,  7, 82, 24, 32,  6,

In [3]:
B = np.random.randint(100, size = (16, 16))
B

array([[98, 66, 52, 68, 49, 53, 79, 38, 36, 52, 74, 46, 60, 28, 88,  0],
       [69, 98, 57, 38, 65, 20, 29, 90,  7, 97, 76, 97, 97, 46, 83, 51],
       [77, 61, 45, 12,  3, 87, 92, 98, 27, 57, 36, 47, 77,  5, 11, 86],
       [32, 16, 22, 24, 52, 10, 93,  6, 23, 37, 46, 85, 44, 52, 40, 24],
       [17, 60, 34, 92, 61, 42, 88, 50, 73, 39, 41, 47,  0, 63, 19, 57],
       [24, 58, 95, 36, 48, 23, 24, 16, 19, 98, 36, 41, 68, 27, 17, 74],
       [59, 40, 73, 51, 42, 42, 88, 21, 92, 13, 88, 97,  5, 91, 36, 82],
       [28, 96, 45, 42, 32,  2, 39, 46, 38, 79,  9, 93, 67, 52, 70, 32],
       [64,  5, 33, 82, 15, 18, 25, 35, 58, 31, 76, 34,  0, 45, 62, 22],
       [75, 71, 60, 46, 77, 33, 50, 13, 44, 77, 33, 63,  2, 69, 97,  6],
       [24, 99,  3, 30, 50, 81, 65, 27, 36, 55, 86,  2, 24, 61, 26, 48],
       [63, 25, 88, 62,  3, 51, 10, 77, 63,  0, 85, 15, 93,  6, 57,  4],
       [50, 38, 87, 40, 40, 64, 25, 95, 65, 96,  2, 78, 12, 87,  2, 34],
       [70, 77, 87, 90, 23, 91, 46, 20,  0, 49, 45,

In [4]:
C = A @ B
C

0:00:00


array([[32865, 39607, 40975, 34086, 31096, 32368, 33263, 32116, 32953,
        42060, 33018, 36387, 28156, 35330, 26711, 27359],
       [46971, 52664, 52545, 49549, 37025, 42526, 43635, 35330, 44902,
        46492, 48515, 51756, 35728, 49493, 41464, 37790],
       [38168, 38898, 40316, 37394, 27857, 36994, 40658, 26352, 29031,
        37914, 31516, 36672, 27157, 35808, 29694, 28014],
       [52759, 45196, 52458, 49055, 25684, 48423, 41499, 39526, 43035,
        40062, 45865, 42863, 35212, 42915, 40793, 31269],
       [43588, 46193, 46426, 39477, 29494, 34976, 31345, 30192, 30680,
        44803, 38687, 39420, 37546, 33677, 40710, 26687],
       [44234, 48073, 43572, 41986, 32985, 34210, 40166, 36965, 32628,
        48019, 38597, 45919, 36259, 38999, 42314, 28983],
       [43375, 47652, 38716, 38680, 29854, 38475, 43581, 28583, 33301,
        43152, 43154, 41749, 33380, 38822, 38016, 32877],
       [43604, 52808, 44969, 41765, 35919, 36471, 43459, 34808, 36859,
        50532, 42604, 4852

In [34]:
def generateHEXdata(A, B):
    
    matrixes = [A, B.T]
    
    for index, matrix in enumerate(matrixes):
        hexData = []
        for row in matrix:
            tempRowHex = ""
            for col in row:
                if col >= 0:
                    tempColHex = hex(col)[2:].zfill(8)
                else:
                    tempColHex = hex((1 << 32) + col)[2:]
                    
                tempRowHex += tempColHex

            tempRowHex = tempRowHex.ljust(128, '0')
            hexData.append(tempRowHex)
            
        for i in range(16):
            
            try:
                x = "repeat(1) @(posedge CLK) #1 DataIn = "
                y ="512'h" + hexData[i]
                z = f"; InAddress = 5'h{index}{hex(i)[2:]}; \n @(posedge CLK) WE = 1;\n @(posedge CLK) WE = 0;"
                
                print(x + y + z)
                
            except IndexError:
                pass
            
        print("\n\n\n\n\n")

In [8]:
generateHEXdata(A, B)

repeat(10) @(posedge CLK) #1 DataIn = 512'h000000100000002800000011000000490000005500000057000000080000001f0000000c000000310000003e0000004c00000063000000050000002800000014; InAddress = 5'h00; WE = 0;
repeat(10) @(posedge CLK) #1 DataIn = 512'h0000000500000053000000030000005400000059000000330000006200000055000000370000000c000000290000003d00000036000000460000006300000035; InAddress = 5'h01; WE = 0;
repeat(10) @(posedge CLK) #1 DataIn = 512'h00000049000000080000003900000049000000510000003d0000002e0000001600000018000000120000000d000000000000003f0000005f0000003200000011; InAddress = 5'h02; WE = 0;
repeat(10) @(posedge CLK) #1 DataIn = 512'h00000056000000020000004800000013000000190000000800000055000000480000005900000000000000210000005100000062000000630000003c00000030; InAddress = 5'h03; WE = 0;
repeat(10) @(posedge CLK) #1 DataIn = 512'h0000004a000000410000001c000000280000000a00000058000000060000005300000022000000340000001b0000003a00000026000000300000003b00000041; InAddress = 5'h04; WE = 0;


## TEST 2

In [3]:
A = np.random.randint(100, size = (4,4))
A

array([[87,  4, 41, 30],
       [33, 47, 52, 77],
       [36, 51,  0, 16],
       [43, 18, 73, 88]])

In [4]:
B = np.random.randint(100, size = (4, 4))
B

array([[49, 42, 71, 95],
       [20,  8, 29, 16],
       [89, 12, 25, 50],
       [58, 70, 99, 76]])

In [6]:
C = A @ B
C

array([[ 9732,  6278, 10288, 12659],
       [11651,  7776, 12629, 12339],
       [ 3712,  3040,  5619,  5452],
       [14068,  8986, 14112, 14711]])

In [11]:
generateHEXdata(A, B)

repeat(1) @(posedge CLK) #1 DataIn = 512'h0000005700000004000000290000001e000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000; InAddress = 5'h00; 
 @(posedge CLK) WE = 1;
 @(posedge CLK) WE = 0;
repeat(1) @(posedge CLK) #1 DataIn = 512'h000000210000002f000000340000004d000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000; InAddress = 5'h01; 
 @(posedge CLK) WE = 1;
 @(posedge CLK) WE = 0;
repeat(1) @(posedge CLK) #1 DataIn = 512'h00000024000000330000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000; InAddress = 5'h02; 
 @(posedge CLK) WE = 1;
 @(posedge CLK) WE = 0;
repeat(1) @(posedge CLK) #1 DataIn = 512'h0000002b000000120000004900000058000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000; InAddress = 5'h03; 
 @(posedge CLK) WE = 1;
 @(posedge CLK) WE = 0;






repeat(1) @(posedge CLK) #1 DataIn

## TEST 3

In [12]:
A = np.random.randint(100, size = (3,8))
A

array([[75, 56, 57, 68, 71, 32, 20, 74],
       [25, 54,  9,  4,  8, 56,  5, 54],
       [10, 35, 50, 85, 25,  5, 35, 81]])

In [13]:
B = np.random.randint(100, size = (8, 5))
B

array([[70, 19,  6,  0, 59],
       [63, 20, 25,  0, 88],
       [52, 87, 89, 93, 18],
       [61, 37,  9, 10, 18],
       [ 5, 17, 29, 90, 95],
       [86, 14, 61, 10, 63],
       [78, 88, 33, 50, 68],
       [46, 14,  3, 90,  2]])

In [14]:
C = A @ B
C

array([[23961, 14471, 12428, 20351, 21872],
       [13594,  4602,  6312,  7267, 11197],
       [17701, 13094,  8578, 16840, 11332]])

In [15]:
generateHEXdata(A, B)

repeat(1) @(posedge CLK) #1 DataIn = 512'h0000004b0000003800000039000000440000004700000020000000140000004a0000000000000000000000000000000000000000000000000000000000000000; InAddress = 5'h00; 
 @(posedge CLK) WE = 1;
 @(posedge CLK) WE = 0;
repeat(1) @(posedge CLK) #1 DataIn = 512'h00000019000000360000000900000004000000080000003800000005000000360000000000000000000000000000000000000000000000000000000000000000; InAddress = 5'h01; 
 @(posedge CLK) WE = 1;
 @(posedge CLK) WE = 0;
repeat(1) @(posedge CLK) #1 DataIn = 512'h0000000a000000230000003200000055000000190000000500000023000000510000000000000000000000000000000000000000000000000000000000000000; InAddress = 5'h02; 
 @(posedge CLK) WE = 1;
 @(posedge CLK) WE = 0;






repeat(1) @(posedge CLK) #1 DataIn = 512'h000000460000003f000000340000003d00000005000000560000004e0000002e0000000000000000000000000000000000000000000000000000000000000000; InAddress = 5'h10; 
 @(posedge CLK) WE = 1;
 @(posedge CLK) WE = 0;
repeat(1) @(posedge CLK) #1 DataIn

## TEST 4

In [23]:
A = np.random.randint(1000, size = (5, 11)) - 500
A

array([[ 234, -422, -245,  -58,  492,  265,  -21,  317,  -84,  -76,   -3],
       [  72,  318,   95, -477,   42,  263, -174,  417,  293, -481,  446],
       [ 441,  222,   42,  -73,  410, -107,  195, -292,  -44,  -24,  -88],
       [  63,  162,  259, -116,  247,  131,  278,   30, -347,  317, -141],
       [ -28,  -92, -356, -246,  -83,   64, -153,  366,  166,  320,  236]])

In [24]:
B = np.random.randint(1000, size = (11, 2)) - 500
B

array([[ 250, -491],
       [ 172,  -40],
       [-142,   20],
       [ 228, -465],
       [-140,  -54],
       [-388, -281],
       [ 437,  180],
       [ 304,  310],
       [ -70, -350],
       [-102, -283],
       [ 224,  418]])

In [25]:
C = A @ B
C

array([[ -64067,  -32833],
       [  21712,  417413],
       [  92205, -252711],
       [ -14042,    3699],
       [  11435,  147104]])

In [35]:
generateHEXdata(A, B)

repeat(1) @(posedge CLK) #1 DataIn = 512'h000000eafffffe5affffff0bffffffc6000001ec00000109ffffffeb0000013dffffffacffffffb4fffffffd0000000000000000000000000000000000000000; InAddress = 5'h00; 
 @(posedge CLK) WE = 1;
 @(posedge CLK) WE = 0;
repeat(1) @(posedge CLK) #1 DataIn = 512'h000000480000013e0000005ffffffe230000002a00000107ffffff52000001a100000125fffffe1f000001be0000000000000000000000000000000000000000; InAddress = 5'h01; 
 @(posedge CLK) WE = 1;
 @(posedge CLK) WE = 0;
repeat(1) @(posedge CLK) #1 DataIn = 512'h000001b9000000de0000002affffffb70000019affffff95000000c3fffffedcffffffd4ffffffe8ffffffa80000000000000000000000000000000000000000; InAddress = 5'h02; 
 @(posedge CLK) WE = 1;
 @(posedge CLK) WE = 0;
repeat(1) @(posedge CLK) #1 DataIn = 512'h0000003f000000a200000103ffffff8c000000f700000083000001160000001efffffea50000013dffffff730000000000000000000000000000000000000000; InAddress = 5'h03; 
 @(posedge CLK) WE = 1;
 @(posedge CLK) WE = 0;
repeat(1) @(posedge CLK) #1 DataIn = 512

In [27]:
hex(-422)

'-0x1a6'

In [33]:
 hex((1 << 32) - 422)[2:]

'fffffe5a'