In [36]:
import numpy as np
from datetime import datetime

In [29]:
A = np.random.randint(100, size = (16,16))
A

array([[ 0, 23, 14,  4, 54,  4, 20, 34, 15, 38, 10, 52, 78, 53, 28,  2],
       [11, 41, 72, 63, 38, 31, 85, 74, 72, 66, 46, 31, 72, 45, 69,  9],
       [99, 27, 76, 40,  7, 11, 41, 50, 37, 47, 98, 41, 68, 70, 64, 96],
       [ 8, 71, 67, 44, 10, 72, 86, 60, 72, 83, 44, 82, 82, 20, 64, 80],
       [77, 27, 20, 42, 24, 81, 21,  1, 93, 52, 85, 57, 85, 94, 56, 71],
       [ 6, 75, 55, 56, 66,  8, 22, 25, 55, 99, 75, 66, 12, 11, 74, 17],
       [16, 99, 58, 45, 79, 18, 35, 43, 15, 69, 78, 78, 98, 27, 71, 44],
       [82,  2, 65, 12, 58, 79, 97, 78, 42, 43,  9, 59, 77,  2, 21, 87],
       [71, 36,  2, 26, 46, 46, 73, 90,  6, 31, 38, 78, 51, 29, 37, 26],
       [ 3, 55, 13, 55, 44, 88, 38, 83, 64, 91, 91, 90, 17, 50, 50,  6],
       [ 6, 96, 43, 27, 50, 78, 75,  7, 91, 43, 92, 90, 99,  3, 87, 27],
       [18, 73, 64, 94, 63, 46, 34, 72, 73, 59, 52, 23, 13, 17, 33, 19],
       [46, 40, 10, 78, 90, 48, 42,  8, 78, 45, 23, 63, 21, 73, 23, 99],
       [84, 11, 77, 29, 50, 98, 87, 78, 75, 93, 57,

In [30]:
B = np.random.randint(100, size = (16, 16))
B

array([[90, 32, 33, 64, 64, 96, 46, 69, 67, 49, 94, 49,  3, 67, 62, 11],
       [82, 91, 77, 54, 61, 23, 68, 49, 73, 66, 23, 52, 12, 36, 39, 30],
       [78, 46,  4,  9, 92, 95, 36, 71, 44, 57, 20, 52, 99, 24, 45, 29],
       [57, 99, 26, 14, 99, 65, 42, 75, 75, 47,  3, 87, 61,  0,  7, 43],
       [12, 58, 91, 15,  2, 62, 32, 20,  8, 62, 99, 90, 42, 72, 54,  5],
       [90, 77, 43, 78, 95, 71, 72, 33, 43, 44, 85, 30,  7, 11, 68, 44],
       [99, 52, 58, 54, 40, 50, 45, 17, 25, 28, 83, 34,  7, 29, 97, 74],
       [67, 27, 57, 30, 90, 58, 54, 70, 23, 99, 59, 38, 79, 58, 22, 88],
       [13, 65, 32, 12, 64, 34,  1, 92, 32, 50, 52,  1, 24, 36, 38,  0],
       [87, 58,  3, 25, 38, 24, 83, 43, 16,  0, 93, 57, 99, 32, 78, 52],
       [36, 45,  0, 96, 76, 49, 75, 61, 26, 31,  7, 43, 50, 85, 43, 87],
       [12, 51, 79, 26, 38, 54, 32, 58, 41, 11, 27,  2, 19, 54, 58,  1],
       [60, 55, 35, 77, 92, 51,  2, 49, 89, 28, 25,  9, 34, 56, 22,  4],
       [32,  8, 13, 99, 44, 99, 97, 87,  0, 28, 17,

In [41]:
t0 = datetime.now()
C = A @ B
time = datetime.now() - t0
print(time * 1e9)
C

0:00:00


array([[22105, 20298, 20828, 21029, 24113, 22934, 20820, 24148, 16583,
        16624, 20648, 19370, 22122, 23976, 22404, 13795],
       [51532, 43169, 33918, 36442, 54800, 43032, 41943, 49242, 33861,
        35808, 39929, 38460, 43165, 36228, 42800, 34878],
       [50341, 38804, 28818, 48598, 59030, 52278, 50869, 50949, 42669,
        33384, 43134, 44483, 43885, 42583, 48548, 35797],
       [57087, 51177, 39302, 44804, 63101, 47684, 50595, 50165, 45341,
        35935, 49156, 40781, 43238, 36554, 52648, 37081],
       [46889, 43923, 31224, 51239, 58037, 51037, 49291, 52057, 41229,
        30943, 44813, 40918, 37971, 42740, 49611, 30463],
       [40919, 40622, 31642, 28657, 42766, 33003, 40692, 42396, 29150,
        28764, 34863, 37280, 38975, 32417, 38236, 28081],
       [49821, 47023, 40056, 42092, 54270, 43666, 47059, 47026, 41103,
        35172, 40864, 43311, 42652, 41472, 44942, 32247],
       [49212, 40127, 34859, 38416, 52388, 49250, 39304, 38076, 38657,
        33308, 53241, 3526

In [32]:
def generateHEXdata(A, B):
    
    matrixes = [A, B.T]
    
    for index, matrix in enumerate(matrixes):
        hexData = []
        for row in matrix:
            tempRowHex = ""
            for col in row:
                tempColHex = hex(col)[2:].zfill(8)
                tempRowHex += tempColHex

            tempRowHex = tempRowHex.ljust(128, '0')
            hexData.append(tempRowHex)
            
        for i in range(16):
            
            try:
                x = " @(posedge CLK) #1 DataIn = "
                y ="512'h" + hexData[i]
                z = f"; InAddress = 5'h{index}{hex(i)[2:]};"
                
                print(x + y + z)
                
            except IndexError:
                pass
            
        print("\n\n\n\n\n")

In [33]:
generateHEXdata(A, B)

 @(posedge CLK) #1 DataIn = 512'h00000000000000170000000e00000004000000360000000400000014000000220000000f000000260000000a000000340000004e000000350000001c00000002; InAddress = 5'h00;
 @(posedge CLK) #1 DataIn = 512'h0000000b00000029000000480000003f000000260000001f000000550000004a00000048000000420000002e0000001f000000480000002d0000004500000009; InAddress = 5'h01;
 @(posedge CLK) #1 DataIn = 512'h000000630000001b0000004c00000028000000070000000b0000002900000032000000250000002f000000620000002900000044000000460000004000000060; InAddress = 5'h02;
 @(posedge CLK) #1 DataIn = 512'h0000000800000047000000430000002c0000000a00000048000000560000003c00000048000000530000002c0000005200000052000000140000004000000050; InAddress = 5'h03;
 @(posedge CLK) #1 DataIn = 512'h0000004d0000001b000000140000002a000000180000005100000015000000010000005d000000340000005500000039000000550000005e0000003800000047; InAddress = 5'h04;
 @(posedge CLK) #1 DataIn = 512'h000000060000004b00000037000000380000004200000008000000160