In [1]:
import numpy as np

In [56]:
A = np.random.randint(100, size = (8,8))
A

array([[64, 78, 23, 20, 50, 98, 93, 71],
       [36, 96, 44, 93,  9, 92, 13, 44],
       [74, 13, 83, 55,  0, 36, 73, 46],
       [75,  4, 22, 58, 94, 58, 22, 72],
       [98, 20, 43, 99, 56, 26, 49, 11],
       [45, 70, 20, 57, 26, 83, 84, 47],
       [24, 66, 84, 54, 12, 66, 58, 99],
       [90, 36, 28, 70, 17, 53, 57, 99]])

In [57]:
B = np.random.randint(100, size = (8,8))
B

array([[31, 80, 94, 53, 65,  8,  8, 13],
       [92, 59, 36, 16, 37,  6, 86, 85],
       [78, 45, 25, 81, 64, 55, 10, 26],
       [70, 85, 70, 68, 79, 33, 21, 98],
       [85, 80, 77, 32, 83, 54, 12, 98],
       [44, 86,  5, 23, 92, 10, 94,  7],
       [76, 82,  8, 29, 24, 31, 86, 10],
       [58, 73, 17, 60, 21, 68, 24,  2]])

In [58]:
A @ B

array([[32102, 37694, 17090, 18674, 26987, 14296, 27384, 16678],
       [28243, 31339, 16455, 18753, 26502, 11154, 21867, 20630],
       [23614, 27537, 14895, 20298, 20978, 12801, 14461, 10689],
       [24859, 31724, 20732, 19065, 26191, 14982, 12582, 17553],
       [25428, 30907, 22958, 20200, 26130, 12087, 12607, 19976],
       [28357, 33012, 15128, 16998, 24095, 11795, 24243, 16704],
       [31222, 32803, 13913, 22328, 24183, 16828, 21554, 15814],
       [27037, 34353, 19069, 21730, 24238, 14733, 18030, 14623]])

In [59]:
def chunk_matrixes(A, size = 3):
    itters = int(np.ceil(A.shape[0] / size))
    result = np.zeros(shape = (itters,itters,size, size))
    
    for i in range(itters):
        for j in range(itters):
            matrix = A[size * i : size * i + size, size * j : size * j + size]
            result[i][j][:matrix.shape[0], :matrix.shape[1]] = matrix
    
    return result.astype(np.uint16)

In [60]:
A_chunked = chunk_matrixes(A, 3)
B_chunked = chunk_matrixes(B, 3)

In [61]:
A_chunked[0][0]

array([[64, 78, 23],
       [36, 96, 44],
       [74, 13, 83]], dtype=uint16)

In [62]:
B_chunked[1][0]

array([[70, 85, 70],
       [85, 80, 77],
       [44, 86,  5]], dtype=uint16)

In [66]:
A_chunked[0][0] @ B_chunked[0][0] + A_chunked[0][1] @ B_chunked[1][0] + A_chunked[0][2] @ B_chunked[2][0]

array([[32102, 37694, 17090],
       [28243, 31339, 16455],
       [23614, 27537, 14895]], dtype=uint16)