In [1]:
import numpy as np
from datetime import datetime

# Generate 2 matrixes

In [11]:
A = np.random.randint(100, size = (16, 16))
A

array([[24, 88, 47, 11, 43, 88, 38, 89, 54, 58, 14, 47, 72, 80, 30, 40],
       [61, 41, 12, 11, 72, 70, 58,  3, 96, 33, 13, 15, 86, 89, 50, 13],
       [ 5, 87, 55, 11, 27, 22, 58, 15, 18, 54, 18, 29, 89, 60, 29, 10],
       [64, 24, 66, 56, 67, 33, 35, 12, 60, 34,  7, 49, 52, 95, 47, 70],
       [46, 58, 19, 60,  4, 84, 98, 65, 69, 17, 60, 73, 75, 21,  7, 39],
       [31, 68, 13, 45, 17, 88, 94, 70, 21, 31, 51,  8,  1, 92, 83, 23],
       [59, 45, 48, 19, 40,  1, 74, 51, 86, 92, 55, 66, 67, 72,  2,  4],
       [89, 61, 80, 29,  5, 42, 36,  4, 37, 82, 10, 60, 97, 48, 48, 80],
       [65, 84, 57, 30, 53, 90, 61, 40, 69, 49, 12, 34, 43, 49, 48, 21],
       [85, 44, 98, 48, 95, 23, 14, 63,  3, 28,  5, 91, 67, 93, 82, 43],
       [56, 49, 28, 27, 15, 43, 90, 67, 75,  6, 88, 48,  4, 79, 63, 16],
       [ 3, 91, 52, 34, 11, 15, 68, 48, 11, 79, 11, 13, 43, 45, 57, 35],
       [ 2, 89, 83, 80, 12,  9, 13,  8,  7, 78, 29, 26, 45, 28, 24, 22],
       [99,  5, 23, 45,  3, 68,  5, 53, 58, 20, 23,

In [12]:
print("{", end="")
for i in range(16):
    temp = str(list(A[i])).replace("[", "{").replace("]", "}").replace(" ", "")
    print(temp, end ="")
    
    if(i != 15):
        print(",")
print("}", end="")

{{24,88,47,11,43,88,38,89,54,58,14,47,72,80,30,40},
{61,41,12,11,72,70,58,3,96,33,13,15,86,89,50,13},
{5,87,55,11,27,22,58,15,18,54,18,29,89,60,29,10},
{64,24,66,56,67,33,35,12,60,34,7,49,52,95,47,70},
{46,58,19,60,4,84,98,65,69,17,60,73,75,21,7,39},
{31,68,13,45,17,88,94,70,21,31,51,8,1,92,83,23},
{59,45,48,19,40,1,74,51,86,92,55,66,67,72,2,4},
{89,61,80,29,5,42,36,4,37,82,10,60,97,48,48,80},
{65,84,57,30,53,90,61,40,69,49,12,34,43,49,48,21},
{85,44,98,48,95,23,14,63,3,28,5,91,67,93,82,43},
{56,49,28,27,15,43,90,67,75,6,88,48,4,79,63,16},
{3,91,52,34,11,15,68,48,11,79,11,13,43,45,57,35},
{2,89,83,80,12,9,13,8,7,78,29,26,45,28,24,22},
{99,5,23,45,3,68,5,53,58,20,23,30,7,81,40,0},
{65,8,7,69,43,65,90,43,64,60,22,28,37,97,67,4},
{88,52,20,13,25,34,84,25,69,21,70,40,71,62,14,90}}

In [13]:
B = np.random.randint(100, size = (16,16))
B

array([[74, 14, 22,  9, 57, 22, 30,  7, 81, 42, 39, 68, 76, 98, 43, 86],
       [23, 27, 88, 21, 59, 97, 64, 73, 27, 32, 80, 47,  0, 91, 30, 94],
       [ 8, 54, 39, 26, 89, 60, 14, 41, 40,  2, 24, 19, 25, 69,  3, 88],
       [53, 89, 63, 76, 19, 53, 11, 34, 34, 97, 57, 99, 71, 60, 85, 51],
       [23,  7,  4,  6, 11, 14, 81, 75,  0, 85, 97, 83,  7, 54, 11, 25],
       [72, 47, 46, 35, 16, 63,  4, 60,  1, 86, 51, 21, 87, 99, 71, 48],
       [52, 32, 48, 17, 45, 70, 35, 80, 52, 17,  3, 87, 39, 38, 20, 61],
       [12, 51, 84, 49, 85,  4, 47, 73, 79, 75, 47, 73, 55, 47, 24, 47],
       [45, 35, 15, 45, 28, 24, 93, 24, 52, 89, 29, 99, 19, 95, 81, 26],
       [54,  1, 73, 72, 95,  6, 68,  5, 78, 29, 93, 80, 80,  8, 66, 50],
       [94, 11, 92, 85, 32, 14, 70, 40, 55, 87, 31, 25, 17, 25, 56, 58],
       [45, 21, 50, 42,  6, 12, 32, 70, 49,  4,  1, 43,  3, 10, 88, 95],
       [61, 33, 91, 77, 74, 18, 39, 74, 65, 50,  3,  9,  8, 36, 39, 24],
       [86, 57, 34, 20, 45, 43, 93,  0, 70, 90, 13,

In [14]:
print("{", end="")
for i in range(16):
    temp = str(list(B[i])).replace("[", "{").replace("]", "}").replace(" ", "")
    print(temp, end ="")
    
    if(i != 15):
        print(",")
print("}", end="")

{{74,14,22,9,57,22,30,7,81,42,39,68,76,98,43,86},
{23,27,88,21,59,97,64,73,27,32,80,47,0,91,30,94},
{8,54,39,26,89,60,14,41,40,2,24,19,25,69,3,88},
{53,89,63,76,19,53,11,34,34,97,57,99,71,60,85,51},
{23,7,4,6,11,14,81,75,0,85,97,83,7,54,11,25},
{72,47,46,35,16,63,4,60,1,86,51,21,87,99,71,48},
{52,32,48,17,45,70,35,80,52,17,3,87,39,38,20,61},
{12,51,84,49,85,4,47,73,79,75,47,73,55,47,24,47},
{45,35,15,45,28,24,93,24,52,89,29,99,19,95,81,26},
{54,1,73,72,95,6,68,5,78,29,93,80,80,8,66,50},
{94,11,92,85,32,14,70,40,55,87,31,25,17,25,56,58},
{45,21,50,42,6,12,32,70,49,4,1,43,3,10,88,95},
{61,33,91,77,74,18,39,74,65,50,3,9,8,36,39,24},
{86,57,34,20,45,43,93,0,70,90,13,90,70,45,10,97},
{50,8,63,30,78,12,92,47,88,7,95,12,32,34,85,6},
{89,15,89,16,60,62,11,0,51,87,34,75,10,83,82,32}}

# Enter the OPEATION and get C matrix

In [15]:
C = (3*A+2*B)@B - B@A 
# C = A@B
C

array([[173900,  78472, 189269, 118478, 181657, 103652, 166319, 136640,
        170558, 192961, 138377, 203331, 110263, 180449, 159763, 202556],
       [166926,  75338, 163040, 107097, 160625, 103165, 149335, 129150,
        146071, 194856, 126796, 194901, 108780, 171467, 140858, 184623],
       [113718,  62773, 150669,  86176, 138525,  92201, 113560, 117662,
        105797, 139690, 103498, 144024,  62664, 130815,  99998, 150068],
       [179037,  83597, 186403, 123625, 175835, 108694, 156698, 128925,
        178402, 181343, 157877, 209313, 109808, 165841, 168983, 212845],
       [162500,  83043, 187316, 136210, 147849, 105593, 128594, 144730,
        160405, 165637, 100702, 180873, 107658, 139785, 154612, 190847],
       [170867,  85160, 191132, 113983, 178800, 106656, 158381, 128217,
        174901, 179063, 153614, 183078, 135493, 152659, 141818, 193146],
       [154666,  70296, 167902, 122389, 169409,  87611, 149515, 138076,
        169880, 159692, 119869, 205170,  98094, 156285, 14

# Generate TEST BENCH Code for testing

In [68]:
memDepth = 12

print("//////////////////////////  Fill A Matrix Data ///////////////////////////////////")
A_offset = 256;
for i in range(16):
    for j in range(16):
        try:
            print("@(posedge clk) #1 MemInAddr  = {}'h{}; MemInData = 32'h{};".format(memDepth, hex(16*i+j + A_offset)[2:],  hex(A[i][15-j])[2:]))
        except IndexError:
            print("@(posedge clk) #1 MemInAddr  = {}'h{}; MemInData = 32'h{};".format(memDepth, hex(16*i+j + A_offset)[2:],  hex(0)[2:]))

            
print("//////////////////////////  Fill B Matrix Data ///////////////////////////////////")
B_offset = 512
for i in range(16):
    for j in range(16):
        try:
            print("@(posedge clk) #1 MemInAddr  = {}'h{}; MemInData = 32'h{};".format(memDepth, hex(16*i+j + B_offset)[2:],  hex(B[i][15-j])[2:]))
        except IndexError:
            print("@(posedge clk) #1 MemInAddr  = {}'h{}; MemInData = 32'h{};".format(memDepth, hex(16*i+j + B_offset)[2:],  hex(0)[2:]))

//////////////////////////  Fill A Matrix Data ///////////////////////////////////
@(posedge clk) #1 MemInAddr  = 12'h100; MemInData = 32'hf;
@(posedge clk) #1 MemInAddr  = 12'h101; MemInData = 32'h1;
@(posedge clk) #1 MemInAddr  = 12'h102; MemInData = 32'h6;
@(posedge clk) #1 MemInAddr  = 12'h103; MemInData = 32'he;
@(posedge clk) #1 MemInAddr  = 12'h104; MemInData = 32'h4;
@(posedge clk) #1 MemInAddr  = 12'h105; MemInData = 32'h5;
@(posedge clk) #1 MemInAddr  = 12'h106; MemInData = 32'h6;
@(posedge clk) #1 MemInAddr  = 12'h107; MemInData = 32'hc;
@(posedge clk) #1 MemInAddr  = 12'h108; MemInData = 32'hb;
@(posedge clk) #1 MemInAddr  = 12'h109; MemInData = 32'h10;
@(posedge clk) #1 MemInAddr  = 12'h10a; MemInData = 32'h13;
@(posedge clk) #1 MemInAddr  = 12'h10b; MemInData = 32'h9;
@(posedge clk) #1 MemInAddr  = 12'h10c; MemInData = 32'h6;
@(posedge clk) #1 MemInAddr  = 12'h10d; MemInData = 32'h5;
@(posedge clk) #1 MemInAddr  = 12'h10e; MemInData = 32'h12;
@(posedge clk) #1 MemInAddr  

# Validate the RESULT with given operation

In [8]:
result = [1252, 1388, 717, 1287, 1282, 1372, 1524, 1222, 1019, 1878, 1349, 1850, 1415, 1080, 1602, 962, 
 1051, 1721, 800, 1275, 1387, 1389, 1524, 1560, 1370, 1810, 1475, 2087, 1385, 1049, 1705, 1465, 
 1077, 1151, 555, 1334, 1374, 1222, 1371, 1202, 1255, 1726, 1358, 1562, 1478, 990, 1421, 1053, 
 1253, 1434, 680, 1407, 1465, 1161, 1580, 1576, 1477, 1699, 1615, 1841, 1373, 1565, 1714, 1257, 
 924, 1301, 536, 1499, 1233, 1347, 1356, 1557, 1275, 1579, 1546, 1600, 1192, 1054, 1513, 1266, 
 1127, 1628, 661, 1859, 1423, 1480, 1759, 1619, 1392, 1868, 1650, 2147, 1596, 1195, 1803, 1315, 
 1539, 1833, 854, 1797, 1865, 1502, 2012, 1736, 1573, 2303, 1962, 2264, 1763, 1372, 1992, 1686, 
 1085, 1218, 689, 1265, 1334, 952, 1529, 1311, 1151, 1635, 1312, 1572, 1482, 1180, 1333, 1029, 
 1203, 1528, 534, 1639, 1648, 1316, 1650, 1509, 1122, 1884, 1461, 2092, 1533, 1403, 1600, 1325, 
 1172, 1704, 625, 1279, 1409, 1234, 1636, 1388, 1274, 1810, 1408, 2007, 1545, 1317, 1647, 1290, 
 786, 1280, 494, 1301, 1329, 1158, 1328, 1419, 1160, 1312, 1343, 1575, 1082, 1226, 1524, 1116, 
 1181, 1603, 719, 1668, 1639, 1623, 1708, 1847, 1534, 1953, 1726, 2009, 1479, 1390, 1949, 1550, 
 1201, 1383, 457, 1511, 1460, 1148, 1744, 1431, 1238, 2033, 1480, 1782, 1634, 1231, 1555, 1209, 
 1057, 1214, 613, 1119, 1336, 1030, 1538, 1224, 1346, 1960, 1180, 1760, 1370, 1030, 1351, 1272, 
 1362, 1574, 687, 1466, 1543, 1332, 1779, 1686, 1410, 2059, 1636, 1966, 1675, 1489, 1948, 1327, 
 962, 1237, 604, 1045, 1167, 1049, 1311, 1244, 1186, 1441, 1245, 1601, 1294, 1126, 1538, 1105]

In [86]:
# result = list(map(int, result.split()))

In [9]:
final_result = True
for i in range(16):
    for j in range(16):
        temp_index = 16*i + j
        g = result[temp_index] == C[i][j]
        final_result = final_result and g

In [10]:
final_result

False